# ===== DATASOURCE =====
spring.datasource.url=jdbc:postgresql://localhost:5432/radar_db
spring.datasource.username= radar_user
spring.datasource.password= radar_psw

# ===== JPA / HIBERNATE =====
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===== LOG =====
spring.jpa.open-in-view=false
